// AUTO GENERATED by fontapi.h.temp, DONT EDIT

#ifndef FONTAPI_H
#define FONTAPI_H

#define FONT_API_VERSION 1

typedef struct lua_State lua_State;
typedef struct fontapi_font fontapi_font;
typedef const char *font_error;

struct font_info {
	int texture_size;
	float edge;
};

struct font_metrics {
	float ascent;
	float descent;
	float line_gap;
};

struct font_underline {
	float position;
	float thickness;
};

struct font_glyph_metrics {
	float offset_x;
	float offset_y;
	float advance_x;
	float advance_y;
	float width;
	float height;
};

struct font_glyph_image {
	int visible;
	float x;
	float y;
	float w;
	float h;
	float u0;
	float v0;
	float u1;
	float v1;
};

enum font_inspect_kind {
	FONT_INSPECT_INFO = 1,
	FONT_INSPECT_METRICS = 2,
	FONT_INSPECT_UNDERLINE = 3,
	FONT_INSPECT_GLYPH_METRICS = 4,
};

struct font_inspect {
	int font_id;
	int size;
	int codepoint;
};

union font_inspect_result {
	struct font_info info;
	struct font_metrics metrics;
	struct font_underline underline;
	struct font_glyph_metrics glyph_metrics;
};

void fontapi_init(lua_State *L);
font_error font_inspect(fontapi_font *font, int kind, const struct font_inspect *inspect, union font_inspect_result *out);
font_error font_resolve_glyph(fontapi_font *font, int font_id, int codepoint, int size, struct font_glyph_image *out);

#endif
