// AUTO GENERATED by fontapi.temp.c, DONT EDIT

#include "fontapi.h"

#include <lauxlib.h>

struct font_api {
	int version;

	font_error (*font_inspect)(fontapi_font *font, int kind, const struct font_inspect *inspect, union font_inspect_result *out);
	font_error (*font_resolve_glyph)(fontapi_font *font, int font_id, int codepoint, int size, struct font_glyph_image *out);
};

static struct font_api API;

font_error
font_inspect(fontapi_font *font, int kind, const struct font_inspect *inspect, union font_inspect_result *out) {
	return API.font_inspect(font, kind, inspect, out);
}

font_error
font_resolve_glyph(fontapi_font *font, int font_id, int codepoint, int size, struct font_glyph_image *out) {
	return API.font_resolve_glyph(font, font_id, codepoint, size, out);
}

struct lua_api;
struct material_api;

struct extlua_apis {
	struct lua_api *lua;
	struct material_api *material;
	struct font_api *font;
};

void
fontapi_init(lua_State *L) {
	struct extlua_apis *apis = *(struct extlua_apis **)lua_getextraspace(L);
	if (apis == NULL || apis->font == NULL || apis->font->version != FONT_API_VERSION) {
		int version = (apis != NULL && apis->font != NULL) ? apis->font->version : 0;
		luaL_error(L, "font api version mismatch, expected %d got %d", FONT_API_VERSION, version);
	}
	API = *apis->font;
}
