-- extlua.h[/.c] generator

local luapath = "../3rd/lua/"

local function parse_params(params)
	local p = {}
	if params == "(void)" then
		return p
	end
	local pn = 1
	for t, n in params:gmatch ("(.-)([%w_.%[%]]+)[,)]", 2) do
		local is_array
		if n:sub(-2) == "[]" then
			is_array = true
			n = n:sub(1, -3)
		end
		p[pn] = { type = t, name = n, is_array = is_array }
		pn = pn + 1
	end
	return p
end

local function get_apis(result, filename, prefix)
	local f = assert(io.open(luapath .. filename))
	local src = f:read "*a"
	f:close()
	local n = #result + 1
	for line in src:gmatch( prefix .. "%s*(.-;)%s*\n" ) do
		if not line:find("...", 1, true) then
			local retv, funcname, params = line:match "([%s%w_*]+)%(([%s%w_]+)%)%s*(%b());$"
			if retv == nil then
				if line:match "%S" then
					error("Invalid function " .. line)
				end
			end
			retv = retv:gsub("%s+$", "")
			if retv:match "%s*void%s*$" then
				retv = "void"
			end
			result[n] = {
				ret = retv,
				name = funcname,
				params = parse_params(params),
			}
			n = n + 1
		end
	end
end

local function decls(params)
	if #params == 0 then
		return "void"
	end
	local r = {}
	for idx, p in ipairs(params) do
		local d = p.type .. p.name
		if p.is_array then
			d = d .. "[]"
		end
		r[idx] = d
	end
	return table.concat(r, ",")
end

local function gen_decl(apis)
	local d = {}
	for idx, item in ipairs(apis) do
		d[idx] = ("\t%s (*%s) (%s);"):format(item.ret, item.name, decls(item.params))
	end
	d[#d+1] = "\tint (*lua_gc) (lua_State *L, int what, ...);"
	return table.concat(d, "\n")
end

local function gen_struct(apis)
	local d = {}
	for idx, item in ipairs(apis) do
		d[idx] = ("\t\t%s,"):format(item.name)
	end
	d[#d+1] = "\t\tlua_gc,"
	return table.concat(d, "\n")
end

local function args(params)
	local args = {}
	for idx, p in ipairs(params) do
		args[idx] = p.name
	end
	return table.concat(args, ",")
end

local impl_fmt = [[
LUA_API %s
%s(%s) {
	%sAPI.%s(%s);
}

]]
local function gen_impl(apis)
	local d = {}
	local n = 1
	for idx, item in ipairs(apis) do
		if item.name ~= "lua_gc" then
			local ret
			if item.ret == "void" then
				ret = ""
			else
				ret = "return "
			end
			local impl = impl_fmt:format(item.ret, item.name, decls(item.params),
				ret, item.name, args(item.params))
			d[n] = impl; n = n + 1
		end
	end
	return table.concat(d)
end

local function readfile(filename)
	local f = assert(io.open(filename))
	local content = f:read "a"
	f:close()
	return content
end

local function genfile(filename, temp)
	local t = readfile(filename)
	local output_filename = filename:gsub("%.temp", "")
	local output_f = assert(io.open(output_filename, "w"))
	output_f:write("// AUTO GENERATED by " .. filename  .. ", DONT EDIT\n\n")
	output_f:write((t:gsub("%$([%w_]+)%$", temp)))
	output_f:close()
end

local apis = {}
get_apis(apis, "lua.h", "LUA_API")
get_apis(apis, "lauxlib.h", "LUALIB_API")

local convert = {
	API_DECL = gen_decl(apis),
	API_STRUCT = gen_struct(apis),
	API_IMPL = gen_impl(apis),
}

genfile("extlua.temp.c", convert)
genfile("extlua_impl.temp.c", convert)
