-- sokolapi.c generator

local header = "../3rd/sokol/sokol_gfx.h"

local allowlist = {
	sg_make_buffer = true,
	sg_destroy_buffer = true,
	sg_update_buffer = true,
	sg_append_buffer = true,
	sg_make_shader = true,
	sg_destroy_shader = true,
	sg_make_pipeline = true,
	sg_destroy_pipeline = true,
	sg_apply_pipeline = true,
	sg_apply_bindings = true,
	sg_apply_uniforms = true,
	sg_draw = true,
	sg_draw_ex = true,
	sg_query_backend = true,
	sg_query_buffer_state = true,
	sg_query_shader_state = true,
	sg_query_pipeline_state = true,
}

local function parse_params(params)
	local p = {}
	if params == "(void)" then
		return p
	end
	local body = params:sub(2, -2)
	local n = 1
	for decl in body:gmatch "[^,]+" do
		local t, name = decl:match "^(.-)([%w_]+)%s*$"
		if not t then
			error("Invalid param " .. decl)
		end
		p[n] = { type = t, name = name }
		n = n + 1
	end
	return p
end

local function readfile(filename)
	local f = assert(io.open(filename))
	local content = f:read "a"
	f:close()
	return content
end

local function get_apis()
	local src = readfile(header)
	local apis = {}
	for line in src:gmatch "SOKOL_GFX_API_DECL%s*(.-;)%s*\n" do
		local retv, name, params = line:match "([%s%w_*]+)%s+(sg_[%w_]+)%s*(%b());$"
		if name and allowlist[name] then
			apis[#apis + 1] = {
				ret = retv:gsub("%s+$", ""),
				name = name,
				params = parse_params(params),
			}
		end
	end
	return apis
end

local function decls(params)
	if #params == 0 then
		return "void"
	end
	local r = {}
	for i, p in ipairs(params) do
		r[i] = p.type .. p.name
	end
	return table.concat(r, ", ")
end

local function args(params)
	local r = {}
	for i, p in ipairs(params) do
		r[i] = p.name
	end
	return table.concat(r, ", ")
end

local function gen_decl(apis)
	local r = {}
	for i, api in ipairs(apis) do
		r[i] = ("\t%s (*%s) (%s);"):format(api.ret, api.name, decls(api.params))
	end
	return table.concat(r, "\n")
end

local function gen_struct(apis)
	local r = {}
	for i, api in ipairs(apis) do
		r[i] = ("\t\t%s,"):format(api.name)
	end
	return table.concat(r, "\n")
end

local function gen_impl(apis)
	local r = {}
	for i, api in ipairs(apis) do
		local ret = api.ret == "void" and "" or "return "
		r[i] = ("SOKOL_GFX_API_DECL %s\n%s(%s) {\n\t%sAPI.%s(%s);\n}\n\n"):format(
			api.ret,
			api.name,
			decls(api.params),
			ret,
			api.name,
			args(api.params)
		)
	end
	return table.concat(r)
end

local function genfile(filename, temp)
	local t = readfile(filename)
	local output = filename:gsub("%.temp", "")
	local f = assert(io.open(output, "w"))
	f:write("// AUTO GENERATED by " .. filename .. ", DONT EDIT\n\n")
	f:write((t:gsub("%$([%w_]+)%$", temp)))
	f:close()
end

local apis = get_apis()
local convert = {
	API_DECL = gen_decl(apis),
	API_STRUCT = gen_struct(apis),
	API_IMPL = gen_impl(apis),
}

genfile("sokolapi.temp.c", convert)
genfile("sokolapi_impl.temp.c", convert)
