-- materialapi.c generator

local apis = {
	{
		ret = "int",
		name = "material_push",
		params = {
			{ type = "lua_State *", name = "L" },
			{ type = "int ", name = "material_id" },
			{ type = "const struct material_push_item *", name = "item" },
		},
	},
}

local function readfile(filename)
	local f = assert(io.open(filename))
	local content = f:read "a"
	f:close()
	return content
end

local function genfile(filename, temp)
	local t = readfile(filename)
	local output = filename:gsub("%.temp", "")
	local f = assert(io.open(output, "w"))
	f:write("// AUTO GENERATED by " .. filename .. ", DONT EDIT\n\n")
	f:write((t:gsub("%$([%w_]+)%$", temp)))
	f:close()
end

local function decls(params)
	if #params == 0 then
		return "void"
	end
	local r = {}
	for i, p in ipairs(params) do
		r[i] = p.type .. p.name
	end
	return table.concat(r, ", ")
end

local function args(params)
	local r = {}
	for i, p in ipairs(params) do
		r[i] = p.name
	end
	return table.concat(r, ", ")
end

local function gen_header_decl()
	local r = { "void materialapi_init(lua_State *L);" }
	for _, api in ipairs(apis) do
		r[#r + 1] = ("%s %s(%s);"):format(api.ret, api.name, decls(api.params))
	end
	return table.concat(r, "\n")
end

local function gen_api_decl()
	local r = {}
	for i, api in ipairs(apis) do
		r[i] = ("\t%s (*%s)(%s);"):format(api.ret, api.name, decls(api.params))
	end
	return table.concat(r, "\n")
end

local function gen_api_struct()
	local r = {}
	for i, api in ipairs(apis) do
		r[i] = ("\t\t%s,"):format(api.name)
	end
	return table.concat(r, "\n")
end

local function gen_api_extern()
	local r = {}
	for i, api in ipairs(apis) do
		r[i] = ("extern %s %s(%s);"):format(api.ret, api.name, decls(api.params))
	end
	return table.concat(r, "\n")
end

local function gen_api_impl()
	local r = {}
	for i, api in ipairs(apis) do
		local ret = api.ret == "void" and "" or "return "
		r[i] = ("%s\n%s(%s) {\n\t%sAPI.%s(%s);\n}\n"):format(
			api.ret,
			api.name,
			decls(api.params),
			ret,
			api.name,
			args(api.params)
		)
	end
	return table.concat(r, "\n")
end

local convert = {
	HEADER_DECL = gen_header_decl(),
	API_DECL = gen_api_decl(),
	API_STRUCT = gen_api_struct(),
	API_EXTERN = gen_api_extern(),
	API_IMPL = gen_api_impl(),
}

genfile("materialapi.h.temp", convert)
genfile("materialapi.temp.c", convert)
genfile("materialapi_impl.temp.c", convert)
