-- solunaapi.c generator

local apis = {
	{
		ret = "void",
		name = "soluna_material_submit",
		params = {
			{ type = "lua_State *", name = "L" },
			{ type = "int ", name = "batch_n" },
			{ type = "void *", name = "ud" },
			{ type = "soluna_material_submit_func ", name = "submit" },
		},
	},
	{
		ret = "int",
		name = "soluna_material_sprite_rect",
		params = {
			{ type = "lua_State *", name = "L" },
			{ type = "void *", name = "bank" },
			{ type = "int ", name = "sprite" },
			{ type = "struct soluna_sprite_rect *", name = "out" },
		},
	},
	{
		ret = "sg_bindings",
		name = "soluna_material_bindings",
		params = {
			{ type = "lua_State *", name = "L" },
			{ type = "void *", name = "bindings" },
		},
	},
	{
		ret = "void",
		name = "soluna_material_push_stream",
		params = {
			{ type = "lua_State *", name = "L" },
			{ type = "int ", name = "material_id" },
			{ type = "int ", name = "count" },
			{ type = "size_t ", name = "payload_size" },
			{ type = "soluna_material_stream_write_func ", name = "write" },
			{ type = "void *", name = "ud" },
		},
	},
	{
		ret = "void",
		name = "soluna_material_stream_read",
		params = {
			{ type = "lua_State *", name = "L" },
			{ type = "const void *", name = "stream" },
			{ type = "int ", name = "index" },
			{ type = "int ", name = "material_id" },
			{ type = "size_t ", name = "payload_size" },
			{ type = "void *", name = "payload" },
			{ type = "struct soluna_material_stream_data *", name = "out" },
		},
	},
}

local type_decl = [[
#define SOLUNA_EXT_API_VERSION 1

struct soluna_sprite_rect {
	int texture;
	float u;
	float v;
	float w;
	float h;
	float ox;
	float oy;
};

struct soluna_material_stream_item {
	float x;
	float y;
	int sprite;
	const void *payload;
};

struct soluna_material_stream_data {
	float x;
	float y;
	int sprite;
};

typedef void (*soluna_material_submit_func)(lua_State *L, void *ud, const void *stream, int n);
typedef void (*soluna_material_stream_write_func)(void *ud, int index, struct soluna_material_stream_item *item);
]]

local host_type_decl = [[
#include <stddef.h>

#include <lua.h>

#include "sokol/sokol_gfx.h"

]] .. type_decl

local function readfile(filename)
	local f = assert(io.open(filename))
	local content = f:read "a"
	f:close()
	return content
end

local function genfile(filename, temp)
	local t = readfile(filename)
	local output = filename:gsub("%.temp", "")
	local f = assert(io.open(output, "w"))
	f:write("// AUTO GENERATED by " .. filename .. ", DONT EDIT\n\n")
	f:write((t:gsub("%$([%w_]+)%$", temp)))
	f:close()
end

local function decls(params)
	if #params == 0 then
		return "void"
	end
	local r = {}
	for i, p in ipairs(params) do
		r[i] = p.type .. p.name
	end
	return table.concat(r, ", ")
end

local function args(params)
	local r = {}
	for i, p in ipairs(params) do
		r[i] = p.name
	end
	return table.concat(r, ", ")
end

local function field_name(api)
	return api.field or api.name:gsub("^soluna_", "")
end

local function impl_name(api)
	return api.impl or field_name(api)
end

local function gen_header_decl()
	local r = { "void solunaapi_init(lua_State *L);" }
	for _, api in ipairs(apis) do
		r[#r + 1] = ("%s %s(%s);"):format(api.ret, api.name, decls(api.params))
	end
	return table.concat(r, "\n")
end

local function gen_api_decl()
	local r = {}
	for i, api in ipairs(apis) do
		r[i] = ("\t%s (*%s) (%s);"):format(api.ret, field_name(api), decls(api.params))
	end
	return table.concat(r, "\n")
end

local function gen_api_struct()
	local r = {}
	for i, api in ipairs(apis) do
		r[i] = ("\t\t%s,"):format(impl_name(api))
	end
	return table.concat(r, "\n")
end

local function gen_api_extern()
	local r = {}
	for i, api in ipairs(apis) do
		r[i] = ("extern %s %s(%s);"):format(api.ret, impl_name(api), decls(api.params))
	end
	return table.concat(r, "\n")
end

local function gen_api_impl()
	local r = {}
	for i, api in ipairs(apis) do
		local ret = api.ret == "void" and "" or "return "
		r[i] = ("%s\n%s(%s) {\n\t%sAPI.%s(%s);\n}\n\n"):format(
			api.ret,
			api.name,
			decls(api.params),
			ret,
			field_name(api),
			args(api.params)
		)
	end
	return table.concat(r)
end

local convert = {
	TYPE_DECL = type_decl,
	HEADER_DECL = gen_header_decl(),
	API_DECL = gen_api_decl(),
	API_STRUCT = gen_api_struct(),
	API_EXTERN = gen_api_extern(),
	API_IMPL = gen_api_impl(),
	HOST_TYPE_DECL = host_type_decl,
}

genfile("solunaapi.h.temp", convert)
genfile("solunaapi.temp.c", convert)
genfile("solunaapi_impl.temp.c", convert)
genfile("../src/extapi_types.temp.h", convert)
