-- fontapi.c generator

local apis = {
	{
		ret = "font_error",
		name = "font_inspect",
		params = {
			{ type = "fontapi_font *", name = "font" },
			{ type = "int ", name = "kind" },
			{ type = "const struct font_inspect *", name = "inspect" },
			{ type = "union font_inspect_result *", name = "out" },
		},
	},
	{
		ret = "font_error",
		name = "font_resolve_glyph",
		params = {
			{ type = "fontapi_font *", name = "font" },
			{ type = "int ", name = "font_id" },
			{ type = "int ", name = "codepoint" },
			{ type = "int ", name = "size" },
			{ type = "struct font_glyph_image *", name = "out" },
		},
	},
}

local function readfile(filename)
	local f = assert(io.open(filename))
	local content = f:read "a"
	f:close()
	return content
end

local function genfile(filename, temp)
	local t = readfile(filename)
	local output = filename:gsub("%.temp", "")
	local f = assert(io.open(output, "w"))
	f:write("// AUTO GENERATED by " .. filename .. ", DONT EDIT\n\n")
	f:write((t:gsub("%$([%w_]+)%$", temp)))
	f:close()
end

local function decls(params)
	if #params == 0 then
		return "void"
	end
	local r = {}
	for i, p in ipairs(params) do
		r[i] = p.type .. p.name
	end
	return table.concat(r, ", ")
end

local function args(params)
	local r = {}
	for i, p in ipairs(params) do
		r[i] = p.name
	end
	return table.concat(r, ", ")
end

local function gen_header_decl()
	local r = { "void fontapi_init(lua_State *L);" }
	for _, api in ipairs(apis) do
		r[#r + 1] = ("%s %s(%s);"):format(api.ret, api.name, decls(api.params))
	end
	return table.concat(r, "\n")
end

local function gen_api_decl()
	local r = {}
	for i, api in ipairs(apis) do
		r[i] = ("\t%s (*%s)(%s);"):format(api.ret, api.name, decls(api.params))
	end
	return table.concat(r, "\n")
end

local function gen_api_struct()
	local r = {}
	for i, api in ipairs(apis) do
		r[i] = ("\t\t%s,"):format(api.name)
	end
	return table.concat(r, "\n")
end

local function gen_api_impl()
	local r = {}
	for i, api in ipairs(apis) do
		local ret = api.ret == "void" and "" or "return "
		r[i] = ("%s\n%s(%s) {\n\t%sAPI.%s(%s);\n}\n"):format(
			api.ret,
			api.name,
			decls(api.params),
			ret,
			api.name,
			args(api.params)
		)
	end
	return table.concat(r, "\n")
end

local convert = {
	HEADER_DECL = gen_header_decl(),
	API_DECL = gen_api_decl(),
	API_STRUCT = gen_api_struct(),
	API_IMPL = gen_api_impl(),
}

genfile("fontapi.h.temp", convert)
genfile("fontapi.temp.c", convert)
genfile("fontapi_impl.temp.c", convert)
