// AUTO GENERATED by materialapi.temp.c, DONT EDIT

#include "materialapi.h"

#include <lauxlib.h>

struct material_api {
	int version;

	int (*material_push)(lua_State *L, int material_id, const struct material_push_item *item);
};

static struct material_api API;

int
material_push(lua_State *L, int material_id, const struct material_push_item *item) {
	return API.material_push(L, material_id, item);
}

static int
material_hook_count(const struct material_hook *hooks) {
	int n = 0;
	for (; hooks->name != NULL; hooks++) {
		n++;
	}
	return n;
}

void
material_push_hooks(lua_State *L, const struct material_hook *hooks) {
	lua_createtable(L, 0, material_hook_count(hooks));
	for (; hooks->name != NULL; hooks++) {
		if (hooks->func.ptr == NULL) {
			lua_pushboolean(L, 0);
		} else {
			lua_pushlightuserdata(L, hooks->func.ptr);
		}
		lua_setfield(L, -2, hooks->name);
	}
}

struct lua_api;
struct font_api;

struct extlua_apis {
	struct lua_api *lua;
	struct material_api *material;
	struct font_api *font;
};

void
materialapi_init(lua_State *L) {
	struct extlua_apis *apis = *(struct extlua_apis **)lua_getextraspace(L);
	if (apis == NULL || apis->material == NULL || apis->material->version != MATERIAL_API_VERSION) {
		int version = (apis != NULL && apis->material != NULL) ? apis->material->version : 0;
		luaL_error(L, "material api version mismatch, expected %d got %d", MATERIAL_API_VERSION, version);
	}
	API = *apis->material;
}
