// AUTO GENERATED by materialapi_impl.temp.c, DONT EDIT

#include "materialapi.h"

extern int material_push(lua_State *L, int material_id, const struct material_push_item *item);

struct material_api {
	int version;

	int (*material_push)(lua_State *L, int material_id, const struct material_push_item *item);
};

struct material_api *
extlua_material_api() {
	static struct material_api api = {
		MATERIAL_API_VERSION,

		material_push,
	};
	return &api;
}
