// AUTO GENERATED by materialapi.h.temp, DONT EDIT

#ifndef MATERIALAPI_H
#define MATERIALAPI_H

#include <lua.h>

#include "sokol/sokol_gfx.h"

#define MATERIAL_API_VERSION 1
#define MATERIAL_DATA_SIZE 12

typedef const char *material_error;

struct material_sprite_rect {
	int texture;
	float u;
	float v;
	float w;
	float h;
	float ox;
	float oy;
};

struct material_item {
	float x;
	float y;
	int transform_index;
	int sprite;
	int texture;
	struct material_sprite_rect rect;
	unsigned char data[MATERIAL_DATA_SIZE];
};

struct material_push_item {
	float x;
	float y;
	float scale;
	float rotation;
	int sprite;
	const void *data;
};

typedef const sg_shader_desc *(*material_shader_desc_func)(sg_backend backend);
typedef void (*material_pipeline_desc_func)(sg_pipeline_desc *desc);
typedef material_error (*material_submit_one_func)(const struct material_item *item, void *instance);
typedef material_error (*material_uniform_one_func)(const struct material_item *item, void *uniform);

union material_hook_func {
	void *ptr;
	material_shader_desc_func shader;
	material_pipeline_desc_func pipeline;
	material_submit_one_func submit;
	material_uniform_one_func uniform;
};

struct material_hook {
	const char *name;
	union material_hook_func func;
};

void material_push_hooks(lua_State *L, const struct material_hook *hooks);

void materialapi_init(lua_State *L);
int material_push(lua_State *L, int material_id, const struct material_push_item *item);

#endif
