// AUTO GENERATED by sokolapi_impl.temp.c, DONT EDIT

#include "sokol/sokol_gfx.h"

struct sokol_api {
	int version;

	sg_buffer (*sg_make_buffer) (const sg_buffer_desc* desc);
	sg_shader (*sg_make_shader) (const sg_shader_desc* desc);
	sg_pipeline (*sg_make_pipeline) (const sg_pipeline_desc* desc);
	void (*sg_destroy_buffer) (sg_buffer buf);
	void (*sg_destroy_shader) (sg_shader shd);
	void (*sg_destroy_pipeline) (sg_pipeline pip);
	void (*sg_update_buffer) (sg_buffer buf,  const sg_range* data);
	int (*sg_append_buffer) (sg_buffer buf,  const sg_range* data);
	void (*sg_apply_pipeline) (sg_pipeline pip);
	void (*sg_apply_bindings) (const sg_bindings* bindings);
	void (*sg_apply_uniforms) (int ub_slot,  const sg_range* data);
	void (*sg_draw) (int base_element,  int num_elements,  int num_instances);
	void (*sg_draw_ex) (int base_element,  int num_elements,  int num_instances,  int base_vertex,  int base_instance);
	sg_backend (*sg_query_backend) (void);
	sg_resource_state (*sg_query_buffer_state) (sg_buffer buf);
	sg_resource_state (*sg_query_shader_state) (sg_shader shd);
	sg_resource_state (*sg_query_pipeline_state) (sg_pipeline pip);
};

struct sokol_api *
extlua_sokol_api() {
	static struct sokol_api api = {
		SOKOL_GFX_INCLUDED,

		sg_make_buffer,
		sg_make_shader,
		sg_make_pipeline,
		sg_destroy_buffer,
		sg_destroy_shader,
		sg_destroy_pipeline,
		sg_update_buffer,
		sg_append_buffer,
		sg_apply_pipeline,
		sg_apply_bindings,
		sg_apply_uniforms,
		sg_draw,
		sg_draw_ex,
		sg_query_backend,
		sg_query_buffer_state,
		sg_query_shader_state,
		sg_query_pipeline_state,
	};
	return &api;
}
