// AUTO GENERATED by sokolapi.temp.c, DONT EDIT

#include <lua.h>

#include "sokol/sokol_gfx.h"

struct sokol_api {
	int version;

	sg_buffer (*sg_make_buffer) (const sg_buffer_desc* desc);
	sg_shader (*sg_make_shader) (const sg_shader_desc* desc);
	sg_pipeline (*sg_make_pipeline) (const sg_pipeline_desc* desc);
	void (*sg_destroy_buffer) (sg_buffer buf);
	void (*sg_destroy_shader) (sg_shader shd);
	void (*sg_destroy_pipeline) (sg_pipeline pip);
	void (*sg_update_buffer) (sg_buffer buf,  const sg_range* data);
	int (*sg_append_buffer) (sg_buffer buf,  const sg_range* data);
	void (*sg_apply_pipeline) (sg_pipeline pip);
	void (*sg_apply_bindings) (const sg_bindings* bindings);
	void (*sg_apply_uniforms) (int ub_slot,  const sg_range* data);
	void (*sg_draw) (int base_element,  int num_elements,  int num_instances);
	void (*sg_draw_ex) (int base_element,  int num_elements,  int num_instances,  int base_vertex,  int base_instance);
	sg_backend (*sg_query_backend) (void);
	sg_resource_state (*sg_query_buffer_state) (sg_buffer buf);
	sg_resource_state (*sg_query_shader_state) (sg_shader shd);
	sg_resource_state (*sg_query_pipeline_state) (sg_pipeline pip);
};

static struct sokol_api API;

SOKOL_GFX_API_DECL sg_buffer
sg_make_buffer(const sg_buffer_desc* desc) {
	return API.sg_make_buffer(desc);
}

SOKOL_GFX_API_DECL sg_shader
sg_make_shader(const sg_shader_desc* desc) {
	return API.sg_make_shader(desc);
}

SOKOL_GFX_API_DECL sg_pipeline
sg_make_pipeline(const sg_pipeline_desc* desc) {
	return API.sg_make_pipeline(desc);
}

SOKOL_GFX_API_DECL void
sg_destroy_buffer(sg_buffer buf) {
	API.sg_destroy_buffer(buf);
}

SOKOL_GFX_API_DECL void
sg_destroy_shader(sg_shader shd) {
	API.sg_destroy_shader(shd);
}

SOKOL_GFX_API_DECL void
sg_destroy_pipeline(sg_pipeline pip) {
	API.sg_destroy_pipeline(pip);
}

SOKOL_GFX_API_DECL void
sg_update_buffer(sg_buffer buf,  const sg_range* data) {
	API.sg_update_buffer(buf, data);
}

SOKOL_GFX_API_DECL int
sg_append_buffer(sg_buffer buf,  const sg_range* data) {
	return API.sg_append_buffer(buf, data);
}

SOKOL_GFX_API_DECL void
sg_apply_pipeline(sg_pipeline pip) {
	API.sg_apply_pipeline(pip);
}

SOKOL_GFX_API_DECL void
sg_apply_bindings(const sg_bindings* bindings) {
	API.sg_apply_bindings(bindings);
}

SOKOL_GFX_API_DECL void
sg_apply_uniforms(int ub_slot,  const sg_range* data) {
	API.sg_apply_uniforms(ub_slot, data);
}

SOKOL_GFX_API_DECL void
sg_draw(int base_element,  int num_elements,  int num_instances) {
	API.sg_draw(base_element, num_elements, num_instances);
}

SOKOL_GFX_API_DECL void
sg_draw_ex(int base_element,  int num_elements,  int num_instances,  int base_vertex,  int base_instance) {
	API.sg_draw_ex(base_element, num_elements, num_instances, base_vertex, base_instance);
}

SOKOL_GFX_API_DECL sg_backend
sg_query_backend(void) {
	return API.sg_query_backend();
}

SOKOL_GFX_API_DECL sg_resource_state
sg_query_buffer_state(sg_buffer buf) {
	return API.sg_query_buffer_state(buf);
}

SOKOL_GFX_API_DECL sg_resource_state
sg_query_shader_state(sg_shader shd) {
	return API.sg_query_shader_state(shd);
}

SOKOL_GFX_API_DECL sg_resource_state
sg_query_pipeline_state(sg_pipeline pip) {
	return API.sg_query_pipeline_state(pip);
}



struct lua_api;
struct soluna_api;

struct extlua_apis {
	struct lua_api * lua;
	struct sokol_api * sokol;
	struct soluna_api * soluna;
};

void
sokolapi_init(lua_State *L) {
	struct extlua_apis *apis = *(struct extlua_apis **)lua_getextraspace(L);
	API = *apis->sokol;
}
