// AUTO GENERATED by solunaapi.h.temp, DONT EDIT

#ifndef SOLUNAAPI_H
#define SOLUNAAPI_H

#include <stddef.h>

#include <lua.h>

#include "sokol/sokol_gfx.h"

#define SOLUNA_EXT_API_VERSION 1

struct soluna_sprite_rect {
	int texture;
	float u;
	float v;
	float w;
	float h;
	float ox;
	float oy;
};

struct soluna_material_stream_item {
	float x;
	float y;
	int sprite;
	const void *payload;
};

struct soluna_material_stream_data {
	float x;
	float y;
	int sprite;
};

struct soluna_material_stream {
	char *data;
	size_t size;
};

typedef const char *soluna_material_error;
typedef void (*soluna_material_submit_func)(void *ud, void *ctx, int n);
typedef void (*soluna_material_stream_write_func)(void *ud, int index, struct soluna_material_stream_item *item);


void solunaapi_init(lua_State *L);
soluna_material_error soluna_material_submit(const void *stream, int prim_n, int material_id, int batch_n, void *ud, soluna_material_submit_func submit);
int soluna_material_sprite_rect(void *bank, int sprite, struct soluna_sprite_rect *out);
sg_bindings soluna_material_bindings(void *bindings);
soluna_material_error soluna_material_push_stream(int material_id, int count, size_t payload_size, soluna_material_stream_write_func write, void *ud, struct soluna_material_stream *out);
void soluna_material_stream_free(void *ptr);
int soluna_material_stream_read(void *ctx, int index, size_t payload_size, void *payload, struct soluna_material_stream_data *out);
void soluna_material_stream_error(void *ctx, const char *error);
int soluna_material_stream_failed(void *ctx);

#endif
