// AUTO GENERATED by solunaapi.temp.c, DONT EDIT

#include "solunaapi.h"

#include <lauxlib.h>

struct soluna_api {
	int version;

	soluna_material_error (*material_submit) (const void *stream, int prim_n, int material_id, int batch_n, void *ud, soluna_material_submit_func submit);
	int (*material_sprite_rect) (struct soluna_sprite_bank bank, int sprite, struct soluna_sprite_rect *out);
	sg_bindings (*material_bindings) (struct soluna_render_bindings bindings);
	soluna_material_error (*material_push_stream) (int material_id, int count, size_t payload_size, soluna_material_stream_write_func write, void *ud, struct soluna_material_stream *out);
	void (*material_stream_free) (void *ptr);
	int (*material_stream_read) (struct soluna_material_stream_context ctx, int index, size_t payload_size, void *payload, struct soluna_material_stream_data *out);
	void (*material_stream_error) (struct soluna_material_stream_context ctx, const char *error);
	int (*material_stream_failed) (struct soluna_material_stream_context ctx);
};

static struct soluna_api API;

soluna_material_error
soluna_material_submit(const void *stream, int prim_n, int material_id, int batch_n, void *ud, soluna_material_submit_func submit) {
	return API.material_submit(stream, prim_n, material_id, batch_n, ud, submit);
}

int
soluna_material_sprite_rect(struct soluna_sprite_bank bank, int sprite, struct soluna_sprite_rect *out) {
	return API.material_sprite_rect(bank, sprite, out);
}

sg_bindings
soluna_material_bindings(struct soluna_render_bindings bindings) {
	return API.material_bindings(bindings);
}

soluna_material_error
soluna_material_push_stream(int material_id, int count, size_t payload_size, soluna_material_stream_write_func write, void *ud, struct soluna_material_stream *out) {
	return API.material_push_stream(material_id, count, payload_size, write, ud, out);
}

void
soluna_material_stream_free(void *ptr) {
	API.material_stream_free(ptr);
}

int
soluna_material_stream_read(struct soluna_material_stream_context ctx, int index, size_t payload_size, void *payload, struct soluna_material_stream_data *out) {
	return API.material_stream_read(ctx, index, payload_size, payload, out);
}

void
soluna_material_stream_error(struct soluna_material_stream_context ctx, const char *error) {
	API.material_stream_error(ctx, error);
}

int
soluna_material_stream_failed(struct soluna_material_stream_context ctx) {
	return API.material_stream_failed(ctx);
}



struct lua_api;
struct sokol_api;

struct extlua_apis {
	struct lua_api * lua;
	struct sokol_api * sokol;
	struct soluna_api * soluna;
};

void
solunaapi_init(lua_State *L) {
	struct extlua_apis *apis = *(struct extlua_apis **)lua_getextraspace(L);
	if (apis == NULL || apis->soluna == NULL || apis->soluna->version != SOLUNA_EXT_API_VERSION) {
		int version = (apis != NULL && apis->soluna != NULL) ? apis->soluna->version : 0;
		luaL_error(L, "soluna ext api version mismatch, expected %d got %d", SOLUNA_EXT_API_VERSION, version);
	}
	API = *apis->soluna;
}
