// AUTO GENERATED by solunaapi.temp.c, DONT EDIT

#include "solunaapi.h"

#include <lauxlib.h>

struct soluna_api {
	int version;

	void (*material_submit) (lua_State *L, int batch_n, void *ud, soluna_material_submit_func submit);
	int (*material_sprite_rect) (lua_State *L, void *bank, int sprite, struct soluna_sprite_rect *out);
	sg_bindings (*material_bindings) (lua_State *L, void *bindings);
	void (*material_push_stream) (lua_State *L, int material_id, int count, size_t payload_size, soluna_material_stream_write_func write, void *ud);
	void (*material_stream_read) (lua_State *L, const void *stream, int index, int material_id, size_t payload_size, void *payload, struct soluna_material_stream_data *out);
};

static struct soluna_api API;

void
soluna_material_submit(lua_State *L, int batch_n, void *ud, soluna_material_submit_func submit) {
	API.material_submit(L, batch_n, ud, submit);
}

int
soluna_material_sprite_rect(lua_State *L, void *bank, int sprite, struct soluna_sprite_rect *out) {
	return API.material_sprite_rect(L, bank, sprite, out);
}

sg_bindings
soluna_material_bindings(lua_State *L, void *bindings) {
	return API.material_bindings(L, bindings);
}

void
soluna_material_push_stream(lua_State *L, int material_id, int count, size_t payload_size, soluna_material_stream_write_func write, void *ud) {
	API.material_push_stream(L, material_id, count, payload_size, write, ud);
}

void
soluna_material_stream_read(lua_State *L, const void *stream, int index, int material_id, size_t payload_size, void *payload, struct soluna_material_stream_data *out) {
	API.material_stream_read(L, stream, index, material_id, payload_size, payload, out);
}



struct lua_api;
struct sokol_api;

struct extlua_apis {
	struct lua_api * lua;
	struct sokol_api * sokol;
	struct soluna_api * soluna;
};

void
solunaapi_init(lua_State *L) {
	struct extlua_apis *apis = *(struct extlua_apis **)lua_getextraspace(L);
	if (apis == NULL || apis->soluna == NULL || apis->soluna->version != SOLUNA_EXT_API_VERSION) {
		int version = (apis != NULL && apis->soluna != NULL) ? apis->soluna->version : 0;
		luaL_error(L, "soluna ext api version mismatch, expected %d got %d", SOLUNA_EXT_API_VERSION, version);
	}
	API = *apis->soluna;
}
