// AUTO GENERATED by solunaapi_impl.temp.c, DONT EDIT

#include <stddef.h>

#include <lua.h>

#include "sokol/sokol_gfx.h"

#define SOLUNA_EXT_API_VERSION 1

struct soluna_sprite_rect {
	int texture;
	float u;
	float v;
	float w;
	float h;
	float ox;
	float oy;
};

struct soluna_material_stream_item {
	float x;
	float y;
	int sprite;
	const void *payload;
};

struct soluna_material_stream_data {
	float x;
	float y;
	int sprite;
};

typedef void (*soluna_material_submit_func)(lua_State *L, void *ud, const void *stream, int n);
typedef void (*soluna_material_stream_write_func)(void *ud, int index, struct soluna_material_stream_item *item);


extern void material_submit(lua_State *L, int batch_n, void *ud, soluna_material_submit_func submit);
extern int material_sprite_rect(lua_State *L, void *bank, int sprite, struct soluna_sprite_rect *out);
extern sg_bindings material_bindings(lua_State *L, void *bindings);
extern void material_push_stream(lua_State *L, int material_id, int count, size_t payload_size, soluna_material_stream_write_func write, void *ud);
extern void material_stream_read(lua_State *L, const void *stream, int index, int material_id, size_t payload_size, void *payload, struct soluna_material_stream_data *out);

struct soluna_api {
	int version;

	void (*material_submit) (lua_State *L, int batch_n, void *ud, soluna_material_submit_func submit);
	int (*material_sprite_rect) (lua_State *L, void *bank, int sprite, struct soluna_sprite_rect *out);
	sg_bindings (*material_bindings) (lua_State *L, void *bindings);
	void (*material_push_stream) (lua_State *L, int material_id, int count, size_t payload_size, soluna_material_stream_write_func write, void *ud);
	void (*material_stream_read) (lua_State *L, const void *stream, int index, int material_id, size_t payload_size, void *payload, struct soluna_material_stream_data *out);
};

struct soluna_api *
extlua_soluna_api() {
	static struct soluna_api api = {
		SOLUNA_EXT_API_VERSION,

		material_submit,
		material_sprite_rect,
		material_bindings,
		material_push_stream,
		material_stream_read,
	};
	return &api;
}
