// AUTO GENERATED by solunaapi.h.temp, DONT EDIT

#ifndef SOLUNAAPI_H
#define SOLUNAAPI_H

#include <stddef.h>

#include <lua.h>

#include "sokol/sokol_gfx.h"

#define SOLUNA_EXT_API_VERSION 1

struct soluna_sprite_rect {
	int texture;
	float u;
	float v;
	float w;
	float h;
	float ox;
	float oy;
};

struct soluna_material_stream_item {
	float x;
	float y;
	int sprite;
	const void *payload;
};

struct soluna_material_stream_data {
	float x;
	float y;
	int sprite;
};

typedef void (*soluna_material_submit_func)(lua_State *L, void *ud, const void *stream, int n);
typedef void (*soluna_material_stream_write_func)(void *ud, int index, struct soluna_material_stream_item *item);


void solunaapi_init(lua_State *L);
void soluna_material_submit(lua_State *L, int batch_n, void *ud, soluna_material_submit_func submit);
int soluna_material_sprite_rect(lua_State *L, void *bank, int sprite, struct soluna_sprite_rect *out);
sg_bindings soluna_material_bindings(lua_State *L, void *bindings);
void soluna_material_push_stream(lua_State *L, int material_id, int count, size_t payload_size, soluna_material_stream_write_func write, void *ud);
void soluna_material_stream_read(lua_State *L, const void *stream, int index, int material_id, size_t payload_size, void *payload, struct soluna_material_stream_data *out);

#endif
