// AUTO GENERATED by ../src/extapi_types.temp.h, DONT EDIT

#ifndef SOLUNA_EXTAPI_TYPES_H
#define SOLUNA_EXTAPI_TYPES_H

#include <stddef.h>

#include "sokol/sokol_gfx.h"

#define SOLUNA_EXT_API_VERSION 1

struct soluna_sprite_rect {
	int texture;
	float u;
	float v;
	float w;
	float h;
	float ox;
	float oy;
};

struct soluna_material_stream_item {
	float x;
	float y;
	int sprite;
	const void *payload;
};

struct soluna_material_stream_data {
	float x;
	float y;
	int sprite;
};

struct soluna_material_stream {
	char *data;
	size_t size;
};

typedef const char *soluna_material_error;
typedef void (*soluna_material_submit_func)(void *ud, void *ctx, int n);
typedef void (*soluna_material_stream_write_func)(void *ud, int index, struct soluna_material_stream_item *item);


#endif
